To Do list: list structure
vabuyia/ToDoList-Apps pull request #1
Opened 2022-04-26 21:27 UTC by vabuyia

In this project, you will build a simple HTML list of To-Do tasks. The list will be styled according to the specifications listed later in this lesson. This simple web page will be built using webpack and served by a webpack dev server.

2022-04-26 23:50 UTC, Gambit142 requested changes
Hi @vabuyia 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-04-26 23:50 UTC, Gambit142 commented on src/index.js
> +    completed: false,
- [ ] Kindly render the tasks according to the `index` values in the array. That means that _**Going to the gym**_ should be the first, _**Going home**_ should be the second and _**Visit Friends and Family**_ should be the third based on the values of the `index`.

2022-04-26 23:50 UTC, Gambit142 commented on src/style.css
> +}
- [ ] Kindly style the application according to the template used in this [video](https://www.youtube.com/watch?v=AcUd-_Yjjqg)

### Template 

![image](https://user-images.githubusercontent.com/77106962/165410580-28889be2-a1ef-4e35-be36-ef168aa9e768.png)

### Your Design

![image](https://user-images.githubusercontent.com/77106962/165410629-7c96a18c-97b5-4150-8e71-eb9f2a0e95f3.png)

2022-04-27 16:13 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @vabuyia, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 16:45 UTC, merged